In [10]:
from pandas import read_csv
from matplotlib import pyplot
# load the dataset
data = read_csv('daily-total-female-births.csv')

In [76]:
import pandas as pd
X_ans=[]
Y_ans=[]
for i in range(len(data["Births"])-3):
    X = list(data["Births"])[i:i+3]
    Y = list(data["Births"])[i+3]
    X_ans.append(X)
    Y_ans.append(Y)
print(Y_ans)
print(X_ans)

[31, 44, 29, 45, 43, 38, 27, 38, 33, 55, 47, 45, 37, 50, 43, 41, 52, 34, 53, 39, 32, 37, 43, 39, 35, 44, 38, 24, 23, 31, 44, 38, 50, 38, 51, 31, 31, 51, 36, 45, 51, 34, 52, 47, 45, 46, 39, 48, 37, 35, 52, 42, 45, 39, 37, 30, 35, 28, 45, 34, 36, 50, 44, 39, 32, 39, 45, 43, 39, 31, 27, 30, 42, 46, 41, 36, 45, 46, 43, 38, 34, 35, 56, 36, 32, 50, 41, 39, 41, 47, 34, 36, 33, 35, 38, 38, 34, 53, 34, 34, 38, 35, 32, 42, 34, 46, 30, 46, 45, 54, 34, 37, 35, 40, 42, 58, 51, 32, 35, 38, 33, 39, 47, 38, 52, 30, 34, 40, 35, 42, 41, 42, 38, 24, 34, 43, 36, 55, 41, 45, 41, 37, 43, 39, 33, 43, 40, 38, 45, 46, 34, 35, 48, 51, 36, 33, 46, 42, 48, 34, 41, 35, 40, 34, 30, 36, 40, 39, 45, 38, 47, 33, 30, 42, 43, 41, 41, 59, 43, 45, 38, 37, 45, 42, 57, 46, 51, 41, 47, 26, 35, 44, 41, 42, 36, 45, 45, 45, 47, 38, 42, 35, 36, 39, 45, 43, 47, 36, 41, 50, 39, 41, 46, 64, 45, 34, 38, 44, 48, 46, 44, 37, 39, 44, 45, 33, 44, 38, 46, 46, 40, 39, 44, 48, 50, 41, 42, 51, 41, 44, 38, 68, 40, 42, 51, 44, 45, 36, 57, 44,

In [77]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
# define dataset
X_birth = array(X_ans)
y_birth = array(Y_ans)
last_id = int(y_birth.shape[0]*0.8)
X_train = X_birth[:last_id]
y_train = y_birth [:last_id]
X_test = X_birth[last_id:]
y_test = y_birth[last_id:]
# define model
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=3))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X_train, y_train, epochs=2000, verbose=0)
# demonstrate prediction
yhat = model.predict(X_test, verbose=0)
print(yhat)
print(y_test)

[[42.318428]
 [41.570705]
 [40.46205 ]
 [40.761505]
 [41.09313 ]
 [38.93011 ]
 [39.56552 ]
 [39.72441 ]
 [35.897377]
 [35.90009 ]
 [38.736034]
 [39.97377 ]
 [42.748898]
 [43.54501 ]
 [44.24673 ]
 [43.255978]
 [41.632046]
 [42.79606 ]
 [43.920246]
 [44.76659 ]
 [44.55446 ]
 [42.39271 ]
 [40.927937]
 [40.39016 ]
 [41.40919 ]
 [40.07111 ]
 [38.393345]
 [38.92111 ]
 [40.07287 ]
 [38.651672]
 [38.334305]
 [42.002724]
 [44.36705 ]
 [43.92703 ]
 [41.45222 ]
 [41.95109 ]
 [45.733803]
 [43.81387 ]
 [43.578068]
 [44.889496]
 [44.37758 ]
 [42.797256]
 [43.675404]
 [44.32918 ]
 [36.17828 ]
 [39.777077]
 [41.55394 ]
 [39.10446 ]
 [37.344265]
 [37.76016 ]
 [39.421062]
 [42.733006]
 [41.841984]
 [39.545822]
 [38.766224]
 [38.97955 ]
 [39.394215]
 [44.572914]
 [44.73034 ]
 [42.220642]
 [41.07396 ]
 [40.764038]
 [41.255814]
 [42.609127]
 [41.7177  ]
 [41.433716]
 [39.92427 ]
 [40.582188]
 [39.487865]
 [38.769176]
 [39.90993 ]
 [44.698242]
 [45.59838 ]]
[42 38 47 38 36 42 35 28 44 36 45 46 48 49 43 42 5

In [56]:
# univariate cnn example
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
# define dataset
X_birth = array(X_ans)
y_birth = array(Y_ans)
last_id = int(y_birth.shape[0]*0.8)
X_train = X_birth[:last_id]
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
y_train = y_birth [:last_id]
X_test = X_birth[last_id:]
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))
y_test = y_birth[last_id:]
# define model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(3, 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X_train, y_train, epochs=1000, verbose=0)
# demonstrate prediction
yhat = model.predict(X_test, verbose=0)
print(yhat)
print(y_test)

[[42.881397]
 [41.740585]
 [38.123795]
 [43.58595 ]
 [36.97761 ]
 [35.020454]
 [38.80299 ]
 [33.80795 ]
 [28.332384]
 [41.20502 ]
 [40.156967]
 [43.9905  ]
 [45.752132]
 [48.06368 ]
 [48.56733 ]
 [42.579067]
 [40.400806]
 [55.17315 ]
 [46.301994]
 [49.588192]
 [45.616493]
 [41.611553]
 [39.789665]
 [38.817547]
 [41.834023]
 [33.855003]
 [33.345753]
 [38.687534]
 [38.452957]
 [34.58661 ]
 [40.920216]
 [46.332005]
 [49.155556]
 [43.420742]
 [39.184544]
 [55.301296]
 [48.67572 ]
 [47.445614]
 [48.99532 ]
 [50.081802]
 [45.790554]
 [43.37784 ]
 [49.400097]
 [44.446957]
 [39.65329 ]
 [44.08011 ]
 [40.402622]
 [32.914158]
 [31.887115]
 [33.160652]
 [47.149723]
 [42.68662 ]
 [42.37168 ]
 [34.661884]
 [36.550903]
 [33.781925]
 [50.45465 ]
 [50.222805]
 [49.24143 ]
 [38.012173]
 [39.185986]
 [41.405113]
 [40.426186]
 [48.377205]
 [37.927013]
 [38.90675 ]
 [37.20917 ]
 [40.317177]
 [33.4262  ]
 [34.100945]
 [50.67931 ]
 [49.50657 ]
 [52.9443  ]]
[43 42 38 47 38 36 42 35 28 44 36 45 46 48 49 43 4

In [58]:
# univariate lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
# define dataset
X_birth = array(X_ans)
y_birth = array(Y_ans)
last_id = int(y_birth.shape[0]*0.8)
X_train = X_birth[:last_id]
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
y_train = y_birth [:last_id]
X_test = X_birth[last_id:]
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))
y_test = y_birth[last_id:]
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(3, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X_train, y_train, epochs=1000, verbose=0)
# demonstrate prediction
yhat = model.predict(X_test, verbose=0)
print(yhat)
print(y_test)

[[43.224964]
 [42.10671 ]
 [38.007458]
 [46.8435  ]
 [38.18216 ]
 [36.111362]
 [41.737225]
 [34.94438 ]
 [28.007652]
 [43.927227]
 [36.032284]
 [44.927334]
 [46.27936 ]
 [48.24793 ]
 [49.497047]
 [43.268505]
 [42.066154]
 [58.98142 ]
 [44.87097 ]
 [51.92903 ]
 [46.49997 ]
 [42.23047 ]
 [40.02857 ]
 [39.990192]
 [44.818657]
 [35.125736]
 [35.190556]
 [39.850433]
 [38.91858 ]
 [32.96843 ]
 [42.2268  ]
 [46.797966]
 [51.391758]
 [44.351982]
 [40.031193]
 [56.902058]
 [49.436222]
 [45.21389 ]
 [49.087406]
 [51.44426 ]
 [46.436855]
 [44.053516]
 [51.968243]
 [45.299004]
 [32.0519  ]
 [46.002716]
 [41.21404 ]
 [34.058426]
 [33.193443]
 [35.925404]
 [48.91383 ]
 [43.24547 ]
 [43.099026]
 [34.090336]
 [38.820824]
 [34.98106 ]
 [52.03854 ]
 [47.21478 ]
 [52.20477 ]
 [39.053036]
 [39.98773 ]
 [41.982742]
 [41.858482]
 [53.07596 ]
 [39.041424]
 [39.956528]
 [38.04064 ]
 [43.782124]
 [34.13882 ]
 [36.906704]
 [51.961697]
 [48.1196  ]
 [54.921944]]
[43 42 38 47 38 36 42 35 28 44 36 45 46 48 49 43 4

In [74]:
import pandas as pd
X_ans=[]
Y_ans=[]
for i in range(len(data["Births"])-4):
    X = list(data["Births"])[i:i+4]
    Y = list(data["Births"])[i+4]
    X_ans.append(X)
    Y_ans.append(Y)

In [75]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import TimeDistributed
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
# define dataset
X_birth = array(X_ans)
y_birth = array(Y_ans)
last_id = int(y_birth.shape[0]*0.8)
X_train = X_birth[:last_id]
# reshape from [samples, timesteps] into [samples, subsequences, timesteps, features]
X_train = X_train.reshape((X_train.shape[0], 2, 2, 1))
y_train = y_birth [:last_id]
X_test = X_birth[last_id:]
# reshape from [samples, timesteps] into [samples, subsequences, timesteps, features]
X_test = X_test.reshape((X_test.shape[0], 2, 2, 1))
y_test = y_birth[last_id:]
# define model
model = Sequential()
model.add(TimeDistributed(Conv1D(filters=64, kernel_size=1, activation='relu'), input_shape=(None, 2, 1)))
model.add(TimeDistributed(MaxPooling1D(pool_size=2)))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X_train, y_train, epochs=500, verbose=0)
yhat = model.predict(X_test, verbose=0)
print(yhat)
print(y_test)

[[43.304028]
 [42.58878 ]
 [41.484917]
 [41.87179 ]
 [41.561424]
 [41.23993 ]
 [41.977074]
 [40.403114]
 [39.293655]
 [40.998947]
 [40.82529 ]
 [41.792816]
 [41.97973 ]
 [42.61465 ]
 [43.042557]
 [43.488697]
 [42.58878 ]
 [45.62969 ]
 [44.0978  ]
 [45.16677 ]
 [45.16677 ]
 [43.624916]
 [42.877697]
 [41.33915 ]
 [41.190002]
 [40.511604]
 [40.175514]
 [41.089607]
 [40.617256]
 [39.92779 ]
 [39.93035 ]
 [40.516087]
 [42.26154 ]
 [43.614185]
 [43.118046]
 [45.511288]
 [43.88856 ]
 [44.53174 ]
 [44.53174 ]
 [44.018852]
 [44.018852]
 [43.486454]
 [44.50621 ]
 [43.547226]
 [43.44345 ]
 [43.624916]
 [42.252316]
 [41.540115]
 [40.221275]
 [39.620533]
 [40.958458]
 [40.779465]
 [42.58878 ]
 [42.58878 ]
 [40.3659  ]
 [40.3659  ]
 [41.383698]
 [41.383698]
 [44.63893 ]
 [44.63893 ]
 [42.48272 ]
 [42.877697]
 [39.93035 ]
 [42.590244]
 [42.590244]
 [42.608078]
 [42.608078]
 [40.320293]
 [40.320293]
 [40.29828 ]
 [43.02645 ]
 [40.590782]
 [45.176743]]
[42 38 47 38 36 42 35 28 44 36 45 46 48 49 43 42 5