In [0]:
import torch
import numpy as np
a = torch.FloatTensor(3, 2)
a

tensor([[1.0116e-36, 0.0000e+00],
        [3.7835e-44, 0.0000e+00],
        [       nan, 0.0000e+00]])

In [0]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [0]:
torch.FloatTensor([[1,2,3],[3,2,1]])

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [0]:
n = np.zeros(shape=(3,2 ))
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [0]:
b = torch.tensor(n)
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [0]:
n = np.zeros(shape=(3,2 ),dtype=np.float32)
torch.tensor(n)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [0]:
n = np.zeros(shape=(3,2 ))
torch.tensor(n,dtype=torch.float32)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [0]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [0]:
s = a.sum()
s

tensor(6)

In [0]:
s.item()

6

In [0]:
a = torch.FloatTensor([2,3])
a

tensor([2., 3.])

In [0]:
ca = a.cuda()
ca

tensor([2., 3.], device='cuda:0')

In [0]:
a + 1

tensor([3., 4.])

In [0]:
ca + 1

tensor([3., 4.], device='cuda:0')

In [0]:
ca.device

device(type='cuda', index=0)

In [0]:
cb = torch.cuda.FloatTensor([2,3])
cb.device

device(type='cuda', index=0)

In [0]:
v1 = torch.tensor([1. , 1.], requires_grad=True)
v2= torch.tensor([2., 2.])
v_sum = v1 + v2
v_res = (v_sum*2).sum()
v_res

tensor(12., grad_fn=<SumBackward0>)

In [0]:
v1.is_leaf, v2.is_leaf

(True, True)

In [0]:
v_sum.is_leaf, v_res.is_leaf

(False, False)

In [0]:
v1.requires_grad, v2.requires_grad

(True, False)

In [0]:
v_sum.requires_grad, v_res.requires_grad

(True, True)

In [0]:
v_res.backward()
v1.grad

tensor([2., 2.])

In [0]:
v2.grad

In [0]:
import torch.nn as nn
s = nn.Sequential(
    nn.Linear(2,5),
    nn.ReLU(),
    nn.Linear(5,20),
    nn.ReLU(),
    nn.Linear(20,10),
    nn.Dropout(p=0.3),
    nn.Softmax(dim=1))
s

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): Dropout(p=0.3)
  (6): Softmax()
)

In [0]:
s(torch.FloatTensor([[1,2]]))

tensor([[0.1491, 0.0934, 0.0907, 0.0478, 0.1142, 0.0810, 0.0876, 0.0977, 0.0562,
         0.1824]], grad_fn=<SoftmaxBackward>)

In [0]:
class OurModule(nn.Module):
    def __init__(self, num_inputs, num_classes, dropout_prob=0.3):
        super(OurModule, self).__init__()
        self.pipe = nn.Sequential(
            nn.Linear(num_inputs, 5),
            nn.ReLU(),
            nn.Linear(5, 20),
            nn.ReLU(),
            nn.Linear(20, num_classes),
            nn.Dropout(p=dropout_prob),
            nn.Softmax(dim=1)
        )

    def forward(self, x):
        return self.pipe(x)


In [0]:
net = OurModule(num_inputs=2, num_classes=3)
print(net)
v = torch.FloatTensor([[2, 3]])
out = net(v)
print(out)
print("Cuda's availability is %s" % torch.cuda.is_available())
if torch.cuda.is_available():
  print("Data from cuda: %s" % out.to('cuda'))


OurModule(
  (pipe): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
    (5): Dropout(p=0.3)
    (6): Softmax()
  )
)
tensor([[0.1453, 0.1401, 0.7146]], grad_fn=<SoftmaxBackward>)
Cuda's availability is True
Data from cuda: tensor([[0.1453, 0.1401, 0.7146]], device='cuda:0', grad_fn=<CopyBackwards>)


In [0]:
pip install tensorboard-pytorch

In [0]:
import math
from tensorboardX import SummaryWriter

writer = SummaryWriter()

funcs = {"sin": math.sin, "cos": math.cos, "tan": math.tan}

for angle in range(-360, 360):
  angle_rad = angle * math.pi / 180
  for name, fun in funcs.items():
    val = fun(angle_rad)
    writer.add_scalar(name, val, angle)
    
writer.close()

In [1]:
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip

--2019-06-10 06:49:15--  https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
Resolving bin.equinox.io (bin.equinox.io)... 3.92.108.98, 54.164.181.42, 54.174.228.92, ...
Connecting to bin.equinox.io (bin.equinox.io)|3.92.108.98|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16648024 (16M) [application/octet-stream]
Saving to: ‘ngrok-stable-linux-amd64.zip.1’

ngrok-stable-linux- 100%[===================>]  15.88M  42.6MB/s    in 0.4s    

2019-06-10 06:49:15 (42.6 MB/s) - ‘ngrok-stable-linux-amd64.zip.1’ saved [16648024/16648024]



In [2]:
!unzip ngrok-stable-linux-amd64.zip

Archive:  ngrok-stable-linux-amd64.zip
replace ngrok? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: ngrok                   


In [0]:
LOG_DIR = './runs'
get_ipython().system_raw(
    'tensorboard --logdir {} --host 0.0.0.0 --port 6006 &'
    .format(LOG_DIR)
)

In [0]:
get_ipython().system_raw('./ngrok http 6006 &')

In [5]:
! curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

http://37fc388f.ngrok.io
